package levianeer.draconis.data.campaign;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.PluginPick;
import com.fs.starfarer.api.campaign.AICoreOfficerPlugin;
import com.fs.starfarer.api.campaign.BaseCampaignPlugin;
import com.fs.starfarer.api.campaign.CampaignFleetAPI;
import com.fs.starfarer.api.campaign.CampaignPlugin;
import com.fs.starfarer.api.campaign.InteractionDialogPlugin;
import com.fs.starfarer.api.campaign.JumpPointAPI;
import com.fs.starfarer.api.campaign.SectorEntityToken;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import com.fs.starfarer.api.campaign.rules.MemoryAPI;
import com.fs.starfarer.api.util.Misc;
import levianeer.draconis.data.campaign.events.XLII_RingPortAssault;
import levianeer.draconis.data.campaign.intel.fafnir.FafnirAccessStrings;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirBlockedDialogPlugin;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirKoriArrivalDialogPlugin;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirRingPortDeliveryDialogPlugin;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirSystemMonitor;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirUnauthorizedEntryDialog;
import levianeer.draconis.data.campaign.intel.sigma_octantis.XLII_SigmaOctantisOfficerPlugin;
import org.apache.log4j.Logger;


public class XLII_CampaignPlugin extends BaseCampaignPlugin {

    private static final Logger log = Global.getLogger(XLII_CampaignPlugin.class);

    public static final String PLUGIN_ID = "XLII_campaignPlugin";
    private static final String FAFNIR_SYSTEM_NAME = "Fafnir";

    @Override
    public String getId() {
        return PLUGIN_ID;
    }

    @Override
    public PluginPick<AICoreOfficerPlugin> pickAICoreOfficerPlugin(String commodityId) {
        if (XLII_SigmaOctantisOfficerPlugin.CORE_ID.equals(commodityId)) {
            return new PluginPick<>(
                new XLII_SigmaOctantisOfficerPlugin(),
                CampaignPlugin.PickPriority.MOD_SPECIFIC
            );
        }
        return null;
    }

    /**
     * Intercepts player interaction with a Fafnir hyperspace entry jump point when access
     * has not yet been granted.
     * <p>
     * {@code autogenerateHyperspaceJumpPoints()} creates NEW JumpPointAPI entities in
     * hyperspace, distinct from the in-system JPs. We identify them by checking whether
     * any in-system Fafnir JP lists the interactionTarget as one of its destinations -
     * the same reverse-lookup used in {@link XLII_FafnirBlockedDialogPlugin}.
     * <p>
     * We do NOT use {@link StarSystemAPI#getAutogeneratedJumpPointsInHyper()} because that
     * list is not serialized; it is empty after a save/load until world-gen runs again.
     */
    @Override
    public PluginPick<InteractionDialogPlugin> pickInteractionDialogPlugin(
            SectorEntityToken interactionTarget) {

        // --- Fafnir unauthorized-entry fleet intercept ---
        // The monitor tags the dispatched fleet with MEM_FLEET_INTERCEPT_TAG and issues
        // an INTERCEPT assignment. When the fleet reaches the player the game triggers a
        // fleet interaction; we intercept it here so our dialog fires instead of the
        // vanilla fleet dialog. Also fires if the player manually clicks the fleet.
        if (interactionTarget instanceof CampaignFleetAPI) {
            CampaignFleetAPI fleet = (CampaignFleetAPI) interactionTarget;
            if (fleet.getMemoryWithoutUpdate().getBoolean(FafnirAccessStrings.MEM_FLEET_INTERCEPT_TAG)) {
                log.debug("Draconis: Fafnir intercept fleet interaction caught");
                MemoryAPI mem = Global.getSector().getMemoryWithoutUpdate();
                boolean isBruteForce = FafnirAccessStrings.PATH_BRUTE_FORCE.equals(
                        mem.getString(FafnirAccessStrings.MEM_ENTRY_PATH));

                if (isBruteForce) {
                    XLII_FafnirSystemMonitor.onBruteForceInterceptFired(fleet, mem);
                    return new PluginPick<>(
                            new XLII_FafnirUnauthorizedEntryDialog(
                                    XLII_FafnirUnauthorizedEntryDialog.EntryType.BRUTE_FORCE,
                                    fleet.getCommander()),
                            CampaignPlugin.PickPriority.MOD_SPECIFIC
                    );
                } else {
                    XLII_FafnirSystemMonitor.onTransverseInterceptFired(fleet, mem);
                    return new PluginPick<>(
                            new XLII_FafnirUnauthorizedEntryDialog(
                                    XLII_FafnirUnauthorizedEntryDialog.EntryType.TRANSVERSE_JUMP,
                                    fleet.getCommander()),
                            CampaignPlugin.PickPriority.MOD_SPECIFIC
                    );
                }
            }
        }

        // --- Kori first-arrival intercept (TT Courier path) ---
        if ("kori".equals(interactionTarget.getId())) {
            var mem = Global.getSector().getMemoryWithoutUpdate();
            if (mem.getBoolean(FafnirAccessStrings.MEM_ACCESS_GRANTED)
                    && FafnirAccessStrings.PATH_TT_COURIER.equals(mem.getString(FafnirAccessStrings.MEM_ENTRY_PATH))
                    && !mem.getBoolean(FafnirAccessStrings.MEM_KORI_ARRIVAL_DONE)) {
                log.debug("Draconis: Kori first-arrival intercept");
                return new PluginPick<>(
                        new XLII_FafnirKoriArrivalDialogPlugin(interactionTarget),
                        CampaignPlugin.PickPriority.MOD_SPECIFIC
                );
            }
        }

        // --- Ring-Port Station intercepts ---
        if ("fafnir_pirate_station".equals(interactionTarget.getId())) {
            var mem = Global.getSector().getMemoryWithoutUpdate();

            // Fafnir Ring-Port contractor delivery (takes priority - one-time, gates Fafnir access)
            if (mem.getBoolean(FafnirAccessStrings.MEM_ACCESS_GRANTED)
                    && FafnirAccessStrings.PATH_RING_PORT.equals(mem.getString(FafnirAccessStrings.MEM_ENTRY_PATH))
                    && !mem.getBoolean(FafnirAccessStrings.MEM_RP_DELIVERY_DONE)) {
                log.debug("Draconis: Ring-Port Station delivery intercept");
                return new PluginPick<>(
                        new XLII_FafnirRingPortDeliveryDialogPlugin(interactionTarget),
                        CampaignPlugin.PickPriority.MOD_SPECIFIC
                );
            }

            // Act 3 assault: fires when mission is active, station is still pirate-controlled, and not yet taken
            com.fs.starfarer.api.campaign.econ.MarketAPI market = interactionTarget.getMarket();
            if (market != null
                    && com.fs.starfarer.api.impl.campaign.ids.Factions.PIRATES.equals(market.getFactionId())
                    && !mem.getBoolean(XLII_RingPortAssault.MEM_TAKEN)
                    && mem.getBoolean("$XLII_blindEyeMissionActive")) {
                log.debug("Draconis: Ring-Port assault intercept");
                return new PluginPick<>(
                        new XLII_RingPortAssault(),
                        CampaignPlugin.PickPriority.MOD_SPECIFIC
                );
            }
        }

        // --- Fafnir hyperspace JP intercept ---
        if (!(interactionTarget instanceof JumpPointAPI)) return null;

        StarSystemAPI fafnir = Global.getSector().getStarSystem(FAFNIR_SYSTEM_NAME);
        if (fafnir == null) return null;

        // Only intercept hyperspace-side entries to Fafnir.
        // Check via in-system JP destinations, which survive save/load.
        boolean leadsToFafnir = false;
        outer:
        for (SectorEntityToken token : fafnir.getJumpPoints()) {
            if (!(token instanceof JumpPointAPI)) continue;
            JumpPointAPI inSystemJP = (JumpPointAPI) token;
            for (JumpPointAPI.JumpDestination dest : inSystemJP.getDestinations()) {
                if (dest.getDestination() == interactionTarget) {
                    leadsToFafnir = true;
                    break outer;
                }
            }
        }
        // Fallback: forward-lookup covers the star corona wormhole, which autogenerateHyperspaceJumpPoints
        // always creates but never populates into any in-system JP's destinations list.
        if (!leadsToFafnir) {
            for (JumpPointAPI.JumpDestination dest : ((JumpPointAPI) interactionTarget).getDestinations()) {
                SectorEntityToken destEntity = dest.getDestination();
                if (destEntity != null && fafnir.equals(destEntity.getContainingLocation())) {
                    leadsToFafnir = true;
                    break;
                }
            }
        }

        if (!leadsToFafnir) return null;

        log.debug("Draconis: Fafnir hyperspace JP interaction intercepted: " + interactionTarget.getId());

        // Bypass: access already granted, or player holds a Draconis commission
        if (Global.getSector().getMemoryWithoutUpdate()
                .getBoolean(FafnirAccessStrings.MEM_ACCESS_GRANTED)
                || "XLII_draconis".equals(Misc.getCommissionFactionId())) {
            return null;
        }

        return new PluginPick<>(
                new XLII_FafnirBlockedDialogPlugin(interactionTarget),
                CampaignPlugin.PickPriority.MOD_SPECIFIC
        );
    }
}