package levianeer.draconis.data.campaign;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.PluginPick;
import com.fs.starfarer.api.campaign.AICoreOfficerPlugin;
import com.fs.starfarer.api.campaign.BaseCampaignPlugin;
import com.fs.starfarer.api.campaign.CampaignFleetAPI;
import com.fs.starfarer.api.campaign.CampaignPlugin;
import com.fs.starfarer.api.campaign.InteractionDialogPlugin;
import com.fs.starfarer.api.campaign.JumpPointAPI;
import com.fs.starfarer.api.campaign.SectorEntityToken;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import com.fs.starfarer.api.campaign.rules.MemoryAPI;
import com.fs.starfarer.api.util.Misc;
import levianeer.draconis.data.campaign.events.XLII_RingPortAssault;
import levianeer.draconis.data.campaign.fleet.DraconisWeaponEscalationMonitor;
import levianeer.draconis.data.campaign.ids.Factions;
import com.fs.starfarer.api.impl.campaign.RuleBasedInteractionDialogPluginImpl;
import levianeer.draconis.data.campaign.intel.blind_eye.XLII_OfficeContactMonitor;
import levianeer.draconis.data.campaign.intel.fafnir.FafnirAccessStrings;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirBlockedDialogPlugin;
import levianeer.draconis.data.campaign.intel.fafnir.XLII_FafnirSystemMonitor;
import levianeer.draconis.data.campaign.intel.longsight.XLII_LongsightOfficerPlugin;
import levianeer.draconis.data.scripts.world.systems.XLII_OfficeSystem;
import org.apache.log4j.Logger;

public class XLII_CampaignPlugin extends BaseCampaignPlugin {

    private static final Logger log = Global.getLogger(XLII_CampaignPlugin.class);

    public static final String PLUGIN_ID = "XLII_campaignPlugin";
    private static final String FAFNIR_SYSTEM_NAME = "Fafnir";

    @Override
    public String getId() {
        return PLUGIN_ID;
    }

    @Override
    public PluginPick<AICoreOfficerPlugin> pickAICoreOfficerPlugin(String commodityId) {
        if (XLII_LongsightOfficerPlugin.CORE_ID.equals(commodityId)) {
            return new PluginPick<>(
                new XLII_LongsightOfficerPlugin(),
                CampaignPlugin.PickPriority.MOD_SPECIFIC
            );
        }
        return null;
    }

    /**
     * Intercepts player interaction with a Fafnir hyperspace entry jump point when access
     * has not yet been granted.
     * <p>
     * {@code autogenerateHyperspaceJumpPoints()} creates NEW JumpPointAPI entities in
     * hyperspace, distinct from the in-system JPs. We identify them by checking whether
     * any in-system Fafnir JP lists the interactionTarget as one of its destinations -
     * the same reverse-lookup used in {@link XLII_FafnirBlockedDialogPlugin}.
     * <p>
     * We do NOT use {@link StarSystemAPI#getAutogeneratedJumpPointsInHyper()} because that
     * list is not serialized; it is empty after a save/load until world-gen runs again.
     */
    @Override
    public PluginPick<InteractionDialogPlugin> pickInteractionDialogPlugin(
            SectorEntityToken interactionTarget) {

        // --- Fafnir unauthorized-entry fleet intercept ---
        // The monitor tags the dispatched fleet with MEM_FLEET_INTERCEPT_TAG and issues
        // an INTERCEPT assignment. When the fleet reaches the player the game triggers a
        // fleet interaction; we intercept it here so our dialog fires instead of the
        // vanilla fleet dialog. Also fires if the player manually clicks the fleet.
        if (interactionTarget instanceof CampaignFleetAPI) {
            CampaignFleetAPI fleet = (CampaignFleetAPI) interactionTarget;
            if (fleet.getMemoryWithoutUpdate().getBoolean(FafnirAccessStrings.MEM_FLEET_INTERCEPT_TAG)) {
                log.debug("Draconis: Fafnir intercept fleet interaction caught");
                MemoryAPI mem = Global.getSector().getMemoryWithoutUpdate();
                boolean isBruteForce = FafnirAccessStrings.PATH_BRUTE_FORCE.equals(
                        mem.getString(FafnirAccessStrings.MEM_ENTRY_PATH));

                if (isBruteForce) {
                    XLII_FafnirSystemMonitor.onBruteForceInterceptFired(fleet, mem);
                    return new PluginPick<>(
                            new RuleBasedInteractionDialogPluginImpl("XLII_FafnirBFIntercept"),
                            CampaignPlugin.PickPriority.MOD_SPECIFIC
                    );
                } else {
                    XLII_FafnirSystemMonitor.onTransverseInterceptFired(fleet, mem);
                    return new PluginPick<>(
                            new RuleBasedInteractionDialogPluginImpl("XLII_FafnirTJIntercept"),
                            CampaignPlugin.PickPriority.MOD_SPECIFIC
                    );
                }
            }
        }

        // --- Daikyu escalation: swap Draconis torpedo loadout if player fields nuclear weapons ---
        if (interactionTarget instanceof CampaignFleetAPI) {
            CampaignFleetAPI fleet = (CampaignFleetAPI) interactionTarget;
            if (DraconisWeaponEscalationMonitor.isEnabled()
                    && fleet.isHostileTo(Global.getSector().getPlayerFleet())
                    && (Factions.DRACONIS.equals(fleet.getFaction().getId())
                        || Factions.FORTYSECOND.equals(fleet.getFaction().getId()))
                    && DraconisWeaponEscalationMonitor.playerHasNuclearWeapons()) {
                DraconisWeaponEscalationMonitor.applyEscalationTo(fleet);
            }
        }

        // --- Office contact fleet: hands over Ladon's coordinates (Blind Eye MEET_THE_DIRECTOR beat) ---
        if (interactionTarget instanceof CampaignFleetAPI) {
            CampaignFleetAPI fleet = (CampaignFleetAPI) interactionTarget;
            if (fleet.getMemoryWithoutUpdate().getBoolean(XLII_OfficeContactMonitor.MEM_FLEET_TAG)) {
                log.debug("Draconis: Office contact fleet interaction intercepted");
                return new PluginPick<>(
                        new RuleBasedInteractionDialogPluginImpl("XLII_OfficeContactScene"),
                        CampaignPlugin.PickPriority.MOD_SPECIFIC
                );
            }
        }

        // --- Office bastion: Monroe vetting intercept (Blind Eye MEET_THE_DIRECTOR beat) ---
        // Gated only on the referral/vetting flags below, deliberately not on
        // XLII_OfficeSystem.ACCESS_GRANTED_FLAG - the escort/travel beat that would flip that
        // flag for real doesn't exist yet, so this is reachable (by console, for now) without it.
        if (interactionTarget instanceof CampaignFleetAPI) {
            CampaignFleetAPI fleet = (CampaignFleetAPI) interactionTarget;
            if (XLII_OfficeSystem.BASTION_ID.equals(fleet.getId())) {
                MemoryAPI mem = Global.getSector().getMemoryWithoutUpdate();
                if (mem.getBoolean("$XLII_officeReferralPending")
                        && !mem.getBoolean("$XLII_officeVettingComplete")) {
                    log.debug("Draconis: Office bastion Monroe vetting intercept");
                    return new PluginPick<>(
                            new RuleBasedInteractionDialogPluginImpl("XLII_MonroeVetting"),
                            CampaignPlugin.PickPriority.MOD_SPECIFIC
                    );
                }
            }
        }

        // --- Kori first-arrival acknowledgement (TT Courier path) is now rules.csv-only ---
        // (MarketPostDock trigger, "# Kori Arrival" section) - no interception needed since
        // it runs inside the market's own dock interaction instead of replacing it. See
        // .claude/systems/fafnir-access.md.

        // --- Ring-Port Station intercepts ---
        if ("fafnir_pirate_station".equals(interactionTarget.getId())) {
            var mem = Global.getSector().getMemoryWithoutUpdate();

            // Ring-Port contractor delivery (TT/RP Fafnir-access path) is now rules.csv-only
            // ("# Ring-Port Delivery" section, MarketPostDock trigger with score:100 to
            // guarantee it outranks XLII_ring_port_transponder_gate and anything else on
            // MarketPostDock at this entity) - no interception needed. See
            // .claude/systems/fafnir-access.md.

            // Act 3 assault: fires when mission is active, station is still pirate-controlled, and not yet taken
            com.fs.starfarer.api.campaign.econ.MarketAPI market = interactionTarget.getMarket();
            if (market != null
                    && com.fs.starfarer.api.impl.campaign.ids.Factions.PIRATES.equals(market.getFactionId())
                    && !mem.getBoolean(XLII_RingPortAssault.MEM_TAKEN)
                    && mem.getBoolean("$XLII_blindEyeMissionActive")) {
                log.debug("Draconis: Ring-Port assault intercept");
                return new PluginPick<>(
                        new XLII_RingPortAssault(),
                        CampaignPlugin.PickPriority.MOD_SPECIFIC
                );
            }
        }

        // --- Fafnir hyperspace JP intercept ---
        if (!(interactionTarget instanceof JumpPointAPI)) return null;

        StarSystemAPI fafnir = Global.getSector().getStarSystem(FAFNIR_SYSTEM_NAME);
        if (fafnir == null) return null;

        // Only intercept hyperspace-side entries to Fafnir.
        // Check via in-system JP destinations, which survive save/load.
        boolean leadsToFafnir = false;
        outer:
        for (SectorEntityToken token : fafnir.getJumpPoints()) {
            if (!(token instanceof JumpPointAPI)) continue;
            JumpPointAPI inSystemJP = (JumpPointAPI) token;
            for (JumpPointAPI.JumpDestination dest : inSystemJP.getDestinations()) {
                if (dest.getDestination() == interactionTarget) {
                    leadsToFafnir = true;
                    break outer;
                }
            }
        }
        // Fallback: forward-lookup covers the star corona wormhole, which autogenerateHyperspaceJumpPoints
        // always creates but never populates into any in-system JP's destinations list.
        if (!leadsToFafnir) {
            for (JumpPointAPI.JumpDestination dest : ((JumpPointAPI) interactionTarget).getDestinations()) {
                SectorEntityToken destEntity = dest.getDestination();
                if (destEntity != null && fafnir.equals(destEntity.getContainingLocation())) {
                    leadsToFafnir = true;
                    break;
                }
            }
        }

        if (!leadsToFafnir) return null;

        log.debug("Draconis: Fafnir hyperspace JP interaction intercepted: " + interactionTarget.getId());

        // Bypass: access already granted, or player holds a Draconis commission
        if (Global.getSector().getMemoryWithoutUpdate()
                .getBoolean(FafnirAccessStrings.MEM_ACCESS_GRANTED)
                || "XLII_draconis".equals(Misc.getCommissionFactionId())) {
            return null;
        }

        return new PluginPick<>(
                new XLII_FafnirBlockedDialogPlugin(interactionTarget),
                CampaignPlugin.PickPriority.MOD_SPECIFIC
        );
    }

}